services:
  fastapi-app:
    build: .
    container_name: fastapi-container
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/fastapi-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level error

  format-code:
    build: .
    container_name: fastapi-format-code
    volumes:
      - .:/fastapi-backend
    working_dir: /fastapi-backend
    command: sh -c "black --config .black . && ruff check --fix"

